#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"
sudo cp by-by.{icns,keylayout} /Library/Keyboard\ Layouts
sudo cp by-ru.{icns,keylayout} /Library/Keyboard\ Layouts
sudo touch /Library/Keyboard\ Layouts
echo "Belarusian keyboard is installed!"
open /System/Library/PreferencePanes/Keyboard.prefPane
